### ISSUE TITLE
Cannot use ESPN+ with this add-on

### ISSUE THREAD

**Issue by lionsnob** [kodi-addons/plugin.video.espn_3#24]
This is really an enhancement request rather than an issue, but it would be really cool to access ESPN+ through this addon. I've attached a tcpdump of me logging into ESPN+ and watching a video.

[ESPNPlusLogin.pcap.txt](https://github.com/kodi-addons/plugin.video.espn_3/files/3539281/ESPNPlusLogin.pcap.txt)

**Comment by t43pasdf** [comment]
I took a look at it, can you try https://github.com/t43pasdf/plugin.video.espn_3/tree/espnplus ?

**Comment by lionsnob** [comment]
Authentication works for both cable and plus but none of the streams will play. Let me grab a log.

**Comment by lionsnob** [comment]
Log attached. Thank you for your effort!
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3655396/kodi.log)

**Comment by t43pasdf** [comment]
Thanks for testing it out, I noticed some issues and pushed changes to git, check it out now

**Comment by lionsnob** [comment]
Hello @t43pasdf - installed the new version and the add-on won't launch. I was able to get into the settings from the Kodi Add-On menu and successfully authenticate though. Log attached.
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3660558/kodi.log)

**Comment by t43pasdf** [comment]
This should fix it - https://github.com/t43pasdf/plugin.video.espn_3/commit/cd8fb9b6cd6761186ca299ccb482e405c8173d47 seems like there was an event with a missing duration.

**Comment by lionsnob** [comment]
Hello - the addon will still not launch. See the attached log and thanks for your persistence!
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3666124/kodi.log)

**Comment by t43pasdf** [comment]
Can you try again with https://github.com/kodi-addons/plugin.video.espn_3/tree/espnplus - I got commit access to add in the updates here.

**Comment by lionsnob** [comment]
It works! I've attached the log in case there's anything useful in it, but all appears good!
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3666332/kodi.log)

**Comment by lionsnob** [comment]
I may have spoken too soon. Every ESPN+ event I select gives the "Your event will start shortly screen". Log attached. Th
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3668294/kodi.log)
anks again!

**Comment by t43pasdf** [comment]
I've seen that a few times as well, I'm not quite sure what the issue is with that just yet, I think it may be related to the authentication token expiring.

**Comment by t43pasdf** [comment]
@lionsnob What about non-live ESPN+ content? Like the series they have underneath Exclusively on ESPN+?

**Comment by MetalChris** [comment]
@t43pasdf I have the same issue as @lionsnob with live events, but as you suggested, I just tried to watch some of the other ESPN+ programming.  I was able to start an episode of Why We Fight, and also was able to start a replay event (I don't remember which one, just picked one at random).  So it seems the add-on is at least partly functional.  So you're pretty close.  Appreciate the work you've put into this so far, you've gotten a lot further than I did.

**Comment by lionsnob** [comment]
Confirmed that non-live events work. Thanks for your continued persistence!

**Comment by t43pasdf** [comment]
I was able to reproduce this using my Android phone, with the same account so I think it may be something deeper causing the issue, can you guys give me some details on what platform/hardware you are running?

**Comment by t43pasdf** [comment]
@lionsnob @MetalChris I think it is fixed with the latest commit in the espnplus branch https://github.com/kodi-addons/plugin.video.espn_3/commit/e29067da1b263d77c962863d1c348374d2ec3971

**Comment by MetalChris** [comment]
@t43pasdf Confirmed ESPN+ live event working on MECOOL M8S PRO W Android TV Box with latest commit.  Thanks!  Nice job!

**Comment by lionsnob** [comment]
@t43pasdf on my Ubuntu 18.04 setup it fails on ESPN+ login. Time for bed, so I’ll get a log tomorrow.

**Comment by lionsnob** [comment]
Log attached.
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3684361/kodi.log)

**Comment by t43pasdf** [comment]
@lionsnob Can you try again? I was working on refactoring some names per PEP and I accidentally changed a JSON key string.

**Comment by MetalChris** [comment]
> @lionsnob @MetalChris I think it is fixed with the latest commit in the espnplus branch [e29067d](https://github.com/kodi-addons/plugin.video.espn_3/commit/e29067da1b263d77c962863d1c348374d2ec3971)

With this commit, live ESPN+ events work for me on my Lubuntu 16.04 system with Kodi 18.4, though it did throw an error if I attempt to check my ESPN+ details in the add-on settings.  After I turned on debugging to get a log, it did not throw the error.  I did capture it though without debugging, if you think it will help, the error is [url=https://pastebin.com/gPg0G86n]here[/url].

**Comment by lionsnob** [comment]
Thanks for getting back @t43pasdf . It still won't work for me - it won't launch nor will it let me authenticate. Log attached. To clarify, I'm supposed to be using the espnplus branch, not the master, correct?
[kodi.log](https://github.com/kodi-addons/plugin.video.espn_3/files/3693818/kodi.log)

**Comment by lionsnob** [comment]
Can confirm what @MetalChris confirmed. It does work with build e29067d.

**Comment by t43pasdf** [comment]
Correct espnplus branch, I'm working on updating the addon to submit it to the official add-on repository so there may have been some broken commits in between, lets keep this open until I can get it released.

**Comment by t43pasdf** [comment]
Going to close this, the version within https://github.com/kodi-addons/repo.kodi-addons should be working.  Let me know if there are any issues/enhancements.
